select * from Company;
select * from Department;
select * from Employee;
select * from FTE;
select * from Contractor;
select * from PartTime;
select * from JobHistory;
select * from Training;
select * from TrainingHistory;
select * from Recruitment;
desc Company;
desc Department;
desc Employee;
desc FTE;
desc Contractor;
desc PartTime;
desc JobHistory;
desc Training;
desc TrainingHistory;
desc Recruitment;